blog/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # path('post/<int:pk>/', views.detail, name='detail'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='detail'),
    # path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    # path('category/<int:pk>', views.category, name='category'),
    path('archives/<int:year>/<int:month>', views.ArchivesView.as_view(), name='archives'),
    path('category/<int:pk>', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>', views.TagView.as_view(), name='tags'),
    # path('search/', views.search, name='search')
]

blogproject2/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.feeds import AllPostRssFeed


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    path('all/rss/', AllPostRssFeed(), name='rss'),
    path('search/', include('haystack.urls'))
]

comments/urls.py
from . import views
from django.urls import path

app_name = 'comments'
urlpatterns = [
    path('comment/post/<int:pk>', views.post_comment, name='post_comment')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
import markdown
from django.utils.html import strip_tags


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=70)
    body = models.TextField()
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()
    excerpt = models.CharField(max_length=200, blank=True)
    category = models.ForeignKey(Category, on_delete=True)
    tags = models.ManyToManyField(Tag, blank=True)
    author = models.ForeignKey(User, on_delete=True)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_time']

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite'
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models
# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post', on_delete=True)

    def __str__(self):
        return self.text[:10]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Category, Tag
# Create your views here.
import markdown
from comments.forms import CommentForm
from django.views.generic import ListView, DetailView
from django.db.models import Q


class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.paginator_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def paginator_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more =False
        right_has_more = False
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range
        if page_number == 1:
            right = page_range[page_number: page_number + 2]
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            if total_pages > 3:
                left = page_range[page_number - 3: page_number - 1]
            else:
                left = page_range[: page_number - 1]
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0: page_number - 1]
            right = page_range[page_number: page_number + 2]
            if left[0] > 1:
                first = True
            if left[0] > 2:
                left_has_more = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first':first,
            'last':last
        }
        return data
# def index(request):
#     # return HttpResponse('欢迎访问我的博客首页')
#     post_list = Post.objects.all().order_by('-created_time')
#     # return render(request, 'blog/index.html', context={'title': '我的博客首页',
#     #                                                    'welcome': '欢迎访问我的博客首页'})
#     return render(request, 'blog/index.html', context={'post_list': post_list})


# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     post.increase_views()
#     post.body = markdown.markdown(post.body, extensions=['markdown.extensions.extra',
#                                                          'markdown.extensions.codehilite',
#                                                          'markdown.extensions.toc'])
#     form = CommentForm()
#     comment_list = post.comment_set.all()
#     comment_count = post.comment_set.count()
#
#     return render(request, 'blog/detail.html', context={'post': post,
#                                                         'form': form,
#                                                         'comment_list': comment_list,
#                                                         'comment_count': comment_count})
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        post = super(PostDetailView, self).get_object(queryset=None)
        # post.body = markdown.markdown(post.body,
        #                               extensions=[
        #                                   'markdown.extensions.extra',
        #                                   'markdown.extensions.codehilite',
        #                                   'markdown.extensions.toc'
        #                               ])
        # return post
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc'
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# def archives(request, year, month):
#     post_list = Post.objects.filter(created_time__year=year,
#                                     created_time__month=month,
#                                     ).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class ArchivesView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        return super(ArchivesView, self).get_queryset().filter(created_time__year=self.kwargs.get('year'),
                                                               created_time__month=self.kwargs.get('month'),
                                                               ).order_by('-created_time')

# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate).order_by('-created_time')
#     return render(request, 'blog/index.html', context={'post_list': post_list})
class CategoryView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# def tags(request, pk):
#     tag = get_object_or_404(Tag, pk=pk)
#     post_list = Post.objects.filter(tags=tag).order_by('-created_time')
#     return render(request, 'blog/index.html', context={"post_list": post_list})

class TagView(ListView):
    model = Tag
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    # if 'q' not in request.GET:
    #     error_msg = '请输入关键词'
    #     return render(request, 'blog/index.html', {'error_msg': error_msg})
    q = request.GET.get('q')
    err_msg = ''
    if not q:
        erros_msg = '请输入正确的关键词'
        return render(request, 'blog/index.html', {'error_msg': err_msg})
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': err_msg,
                                               'post_list': post_list})

templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                {% for tag in post.tags.all %}
                    <span class="post-tag"><a href="#">{{ tag.name }}</a></span>
                {% endfor %}
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ comment_count }}评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱:</label>
                    {{ form.email }}
                    {{ form.email.error }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">URL:</label>
                    {{ form.url }}
                    {{ form.url.error }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.text.id_for_label }}">评论:</label>
                    {{ form.text }}
                    {{ form.tex.error }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>
        </form>
        <div class="comment-list-panel">
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
                </li>
            {% empty %}
                暂无评论
            {% endfor %}
        </ul>
        </div>
    </section>
{% endblock main %}
{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
            {{ post.toc|safe }}
{#        <ul>#}
{#            <li>#}
{#                <a href="#">教程特点</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">谁适合这个教程</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">在线预览</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">资源列表</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">获取帮助</a>#}
{#            </li>#}
{#        </ul>#}
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}
    {% for post in post_list %}
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">Django 博客教程</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="#">{{ post.comment_set.count }}评论</a></span>
                    <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>文章摘要:{{ post.excerpt }}</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="'no-post">暂时还没有发布的文章!</div>
    {% endfor %}
    {% if is_paginated %}
        <div class="pagination">
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color:red">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
{#    <div class="pagination-simple">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
{#        {% endif %}#}
{#        <span class="current">第 {{ page_obj.number }} 页/ 共 {{ paginator.num_pages }} 页</span>#}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#        {% endif %}#}
        </div>
    {% endif %}
    <div class="rss">
        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span>RSS 订阅</a>
    </div>
{#        <ul>#}
{#            <li><a href="">1</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">4</a></li>#}
{#            <li><a href="">5</a></li>#}
{#            <li class="current"><a href="">6</a></li>#}
{#            <li><a href="">7</a></li>#}
{#            <li><a href="">8</a></li>#}
{#            <li><a href="">...</a></li>#}
{#            <li><a href="">11</a></li>#}
{#        </ul>#}
{#    </div>#}
{#    </div>#}
{% endblock  %}
{#<aside class="col-md-4">#}
{#    <div class="widget widget-recent-posts">#}
{#        <h3 class="widget-title">最新文章</h3>#}
{#        <ul>#}
{#            <li>#}
{#                <a href="#">Django 博客开发入门教程：前言</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Django 博客使用 Markdown 自动生成文章目录</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">部署 Django 博客</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#    <div class="widget widget-archives">#}
{#        <h3 class="widget-title">归档</h3>#}
{#        <ul>#}
{#            <li>#}
{#                <a href="#">2017 年 5 月</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">2017 年 4 月</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">2017 年 3 月</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{##}
{#    <div class="widget widget-category">#}
{#        <h3 class="widget-title">分类</h3>#}
{#        <ul>#}
{#            <li>#}
{#                <a href="#">Django 博客教程 <span class="post-count">(13)</span></a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Python 教程 <span class="post-count">(11)</span></a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Django 用户认证 <span class="post-count">(8)</span></a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{##}
{#    <div class="widget widget-tag-cloud">#}
{#        <h3 class="widget-title">标签云</h3>#}
{#        <ul>#}
{#            <li>#}
{#                <a href="#">Django</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Python</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Java</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">笔记</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">文档</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">AngularJS</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">CSS</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">JavaScript</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">Snippet</a>#}
{#            </li>#}
{#            <li>#}
{#                <a href="#">jQuery</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#    <div class="rss">#}
{#        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>#}
{#    </div>#}
{#</aside>#}